---
apiVersion: v1
kind: Service
metadata:
  name: counting
spec:
  selector:
    app: counting
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: counting
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
spec:
  replicas: 1
  selector:
    matchLabels:
      service: counting
      app: counting
  template:
    metadata:
      labels:
        service: counting
        app: counting
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: counting
      containers:
      - name: counting
        image: obsidianio/server
        ports:
          - containerPort: 8080