---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: dashboard
spec:
  protocol: "grpc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dashboard
      app: dashboard
  template:
    metadata:
      labels:
        service: dashboard
        app: dashboard
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "counting:8090"
    spec:
      serviceAccountName: dashboard
      containers:
      - name: dashboard
        image: obsidianio/front
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SERVER_ADDR
          value: "localhost:8090"